project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "R-multiverse"
  description: "A community-curated package repository system, powered by R-universe"
  site-url: "https://r-multiverse.org"
  favicon: "logo/logo-hexbin.png"
  image: "logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "logo/logo-hexbin.png"
    logo-alt: "R-multiverse"
    left:
    - text: "About"
      menu:
        - community.qmd
        - production.qmd
    - users.qmd
    - contributors.qmd
    - team.qmd
    - text: "Policies"
      menu:
        - review.md
        - conduct.md
        - text: Governance Document
          url: governance.md
        - security.md
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-multiverse/contributions
          - text: Report Issue
            url: https://github.com/r-multiverse/help
      - icon: rocket-takeoff
        aria-label: "R-multiverse Community Universe"
        href: https://community.r-multiverse.org
  page-footer:
    center: "&copy; 2024 the R-multiverse project."

format:
  html:
    theme: cosmo
    toc: true
