on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 * 15-22 3 *'  # March 15-22 every hour on the hour
    - cron: '0 * 15-22 6 *'  # June 15-22 every hour on the hour
    - cron: '0 * 15-22 9 *'  # September 15-22 every hour on the hour
    - cron: '0 * 15-22 12 *' # December 15-22 every hour on the hour

name: render
permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R package dependencies.
        run: install.packages(c("gt", "knitr", "rmarkdown", "rversions"))
        shell: Rscript {0}

      - name: Cache results
        uses: actions/cache@v4.2.0
        with:
          path: |
            docs
            _freeze
          key: site-render-${{ hashFiles('**/*md') }}
          restore-keys: site-render-

      - name: Render
        run: quarto render

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
